### ISSUE TITLE
请问能自定义样式吗？

### ISSUE THREAD

**Issue by caecfd** [LuckyPuppy514/Bilibili-Markdown#1]
能自定义采用脚本转化后的样式么？还有就是数学公式能否支持呢？

**Comment by LuckyPuppy514** [comment]
1. 自定义转换，可以做但是实用性不大了，因为B站支持的 html 和 css 都是有限制的，基本上就改不了了；
2. 数学公式是可以的，就是我本来想先看看用得人多不多再做，因为我自己用不上，结果有点冷清 🤣，只能等有时间再弄了，有兴趣可以关注下这个项目，或者关注我B站 😁

**Comment by LuckyPuppy514** [comment]
最新版已支持数学公式，[升级最新版即可 👆](https://greasyfork.org/zh-CN/scripts/452683-bilibili-markdown)（如果不行，则需要清除下浏览器缓存）

![image](https://user-images.githubusercontent.com/53246532/210540000-ff8fa4e1-cb0b-4ff1-a326-06b00cd69b9b.png)

**Comment by caecfd** [comment]
您好，已收到您的邮件，我会在最短的时间内给您回复，谢谢！

**Comment by faithererer** [comment]
同求一个自定义样式+-+

**Comment by caecfd** [comment]
您好，已收到您的邮件，我会在最短的时间内给您回复，谢谢！
