### ISSUE TITLE
在Firefox 上脚本失效

### ISSUE THREAD

**Issue by ghost** [LuckyPuppy514/Bilibili-Markdown#2]
Firefox 版本 108.0 (64 位) ，脚本安装后在专栏编辑页面不会出现按钮，关闭所有其余扩展和油猴中的其余脚本后情况仍然复现。GM/FF 兼容选项 也全部打开。
请问可以修复吗

**Comment by LuckyPuppy514** [comment]
你是什么系统，Firefox 是正式版么，我这边最新版版本号是 107，一切正常

![image](https://user-images.githubusercontent.com/53246532/206196017-a1b5c2b9-930d-4288-a7ee-ac6155edb24e.png)
