### ISSUE TITLE
近期脚本使用问题

### ISSUE THREAD

**Issue by FrankHB** [LuckyPuppy514/Bilibili-Markdown#3]
# 环境

浏览器和扩展 Edge 111.0.1661.54 + Tamper monkey 4.18.1 。

脚本版本 1.0.3 。

# 问题

因为同环境有几个问题，暂时先放着当 meta bug ，如果需要可以拆 issue 。

## CSR

好像默认没法用。找了个 Content Security Policy Overrider 自己编辑了一下。

## 反复自动重新加载

这个导致根本没法用。具体症状是保存后还是空白，然后不知怎么回事就抽风了切换回原编辑器没几秒就自动刷新重新加载整个投稿页面，循环……

看了一下控制台，编辑器页面有异常，断进去 `bilibiliMarkdown[event.data.method](param)` 的 `[]` 里面直接 `undefined` 了。确实有个什么 XHR 的事件的 `event.data` 里没 `method` 的情况，需要判断一下。

脚本里也有类似的一个地方要改。

因为不确定还有多少问题，不想改一次 commit 一次，浪费一个午休折腾部署了个 VSC+ Live Server + 自签名证书。万幸改完了倒是能用了……

## SessionBox 不兼容

就这里还是没法用，保存就 404 不成功。这个不想折腾了，直接另外开个 InPrivate 窗口重新登录了，倒是能用……

## Markdown 支持

不太清楚具体支持的语法，有文档指引嘛？

比如平时偷懒用 VS 自带的直接编辑，能认识这种：

```markdown
<span style="color: red">***XXX**: xxx*</span>
```

GFM 显然至少是认识标签内的东西的，效果：

<span style="color: red">***XXX**: xxx*</span>

到这就认不全连续的星号了，只能：

```markdown
*<span style="color: red">**XXX**: xxx</span>*
```

**Comment by FrankHB** [comment]
语法问题：好吧，[上游就一堆 WIP](https://marked.js.org/#specifications)……

**Comment by LuckyPuppy514** [comment]
![20230327145742](https://user-images.githubusercontent.com/53246532/227865365-38fcc99d-5d5b-4049-9ddf-1fdd19dd72e9.gif)

edge 最新版，win11，tampermonkey  v4.18.1

1. CSR 问题，我没遇到过
2. 反复自动加载，我也没遇到过
3. SessionBox 不兼容问题，我个人并未使用 SessionBox，所以没做兼容性测试
4. 支持的语法，REDAME 就有，还有B站专栏效果演示，请自行查阅

看你的问题，大概率都是因为其他脚本或插件不兼容导致的，建议在B站专栏页面尽量关闭其他脚本或插件，实在有必要的并且冲突的，请附上详细脚本或插件地址，操作流程，报错截图等信息，我会尝试进行兼容（没法保证做到兼容任意脚本和插件）

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/227870346-84b4691f-864e-41b3-8b63-76bd99d2b005.png)

还有这个也是没问题的（斜体B站本身就不支持）

```
<span style="color: red">***XXX**: xxx*</span>

*<span style="color: red">**XXX**: xxx</span>*
```

**Comment by FrankHB** [comment]
测试时当然是关了其它脚本的，其它有影响的主要就 uBlock Origin 和 NoScript ，也禁用了。

再试了下，重新加载也不是每次必现的，有一段时间大概率连续出现（不管就一直自动重新加载下去了），现在是没有。

不过还是有别的问题。

![CSR](https://user-images.githubusercontent.com/1857647/227990516-fb87cbcc-5b33-4653-93d6-f3d9d84d9fa1.png)

![image](https://user-images.githubusercontent.com/1857647/227991519-a51c29d2-f416-40e0-bd40-f2432d9d56c4.png)

别的可能有环境不干净的问题……（我再试试搭个纯净的环境再重现下看看），但语法差别这就真的见鬼了。然后我现在居然没法重现（要是上下文相关就没救了，之前发现不行之后别的地方也给编辑了）……因为原来有问题的效果是在预览界面就直接多出来 `*` 而不是忽略，所以看来也不是 B 站不支持斜体的原因。那么这个就先视为解决（本来就得预期没法保证完全兼容，就算有问题也容易变通）。

说起来 B 站不支持外链还好理解，支持粗体却不支持斜体是个什么逻辑？

**Comment by FrankHB** [comment]
现在没法重现了，之前有自动反复重新加载的错误截图：

![image](https://user-images.githubusercontent.com/1857647/227995814-adfdf215-4eab-42eb-8e38-fea1e85e7fb6.png)

那时候没关掉 uBlock Origin ，但是关掉了也一样，就是少掉了几个 `net::ERR_BLOCKED_BY_CLIENT` 而已。

`event.data` 是有的，但是里面没 `method` ，不过具体是啥没记下来现在也找不到了，就记得里面有 `XHR` 。我寻思好像也没别的扩展和脚本在这里搞事……能排除是 B 站的服务器捣鬼么？

**Comment by LuckyPuppy514** [comment]
![20230328000634](https://user-images.githubusercontent.com/53246532/227999110-2845b552-ea1a-42ea-a467-c905b913e227.gif)

你说的问题我一个也没遇到 😂 （除了不影响效果的两个 Report Only），而且我的浏览器和油猴版本跟你的一样

![image](https://user-images.githubusercontent.com/53246532/228000271-634e16fe-8e4f-42db-8b20-95a59b2e5c4f.png)
![image](https://user-images.githubusercontent.com/53246532/228000368-cd2082ff-3966-42b9-ba80-4af044b0d6b6.png)
![image](https://user-images.githubusercontent.com/53246532/228000438-da29bdc7-d118-4207-92af-70443ecde397.png)

**Comment by FrankHB** [comment]
![image](https://user-images.githubusercontent.com/1857647/228112521-3fedd2dd-cf77-4c79-9e58-61c770365fd7.png)

就系统版本稍微不一样。

现在不会自动重载页面了，但是不用自己魔改的版本，保存了切换回原编辑器还是有可能空白……最扯的是好像也不是总是重现。

好像之前看专栏回复也有人遇到保存后空白？

这几周按计划欠了一堆文档要完成（顺带某些发 B 站所以折腾这个），等空了换个纯净对比看看，再分析一下看看是否可以保证重现……

另外实现 B 站原始的插入图片下面添加注释的效果怎么比较好？手动 `<figure>` 贴 URL 感觉有点蠢，不知道是不是实际效果能多端保持兼容。

**Comment by LuckyPuppy514** [comment]
1. 大哥，这里不是聊天的地方，有问题请先理清你的问题，提供复现问题的环境，操作，截图等信息
2. 图片注释我本身没实现，因为个人习惯 markdown 图片都是不带注释的，有需要就是你可以自己加 html 代码

```html
![banner](http://article.biliimg.com/bfs/article/9817fa4328a0025655f40f58b1bbad8894b3cac5.png)

<figcaption class="caption" contenteditable="false">图片注释</figcaption>
```

如果其他平台格式不一样，可以自己批量替换，至于有什么其他办法，就得你自己研究了

**Comment by FrankHB** [comment]
试了下，虽然不认斜体的标签，用 `font-style: italic` 样式是可以实现的。因为是通用的 Markdown 语法，可以考虑加上。

现在问题暂时已经变通。如果发现新的稳定重现再另外开 issue 。
