### ISSUE TITLE
[Report Only] Refused to frame 'https://www.lckp.top/' because it violates the following Content Security Policy directive: "default-src 'self' data: *.bilibili.com *.hdslb.com". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

### ISSUE THREAD

**Issue by xiaoyuanreadbook** [LuckyPuppy514/Bilibili-Markdown#4]
- 环境：mac和Windows都试过了，用的是chrome浏览器
- 问题：启用工具后页面没有反应，工具无法正常显示，
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/2fc5473a-7b95-4e41-8190-d81959539408)
- developer tools报错好像是csp的问题
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/5a172494-f87c-4bb8-9683-dcca958eb9c7)

**Comment by LuckyPuppy514** [comment]
我看你连标题都没有，怎么可能切换过去，不是有提示么

![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53246532/fed8bae3-263a-43f3-88fb-58c74bd2caae)

**Comment by xiaoyuanreadbook** [comment]
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/529bf7e5-a76a-4f56-b852-d2213ddd11c5)
还是不行的，我之前有尝试过输入标题，但是上次的截图没有带上标题。

**Comment by xiaoyuanreadbook** [comment]
麻烦您了

**Comment by LuckyPuppy514** [comment]
截图请像我上面那样，截图全屏
F12 打开控制台后先清理一次日志，再重新操作，然后再重新截图

**Comment by xiaoyuanreadbook** [comment]
![1691688692240_ pic_hd](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/839dfe12-513d-4686-ae6b-aa77c49a78f3)
![1701688692240_ pic_hd](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/70505091-bad8-4a83-ba6b-50b8c282488e)
![1711688692240_ pic_hd](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/138704734/2005b61f-2c6a-40ce-b282-04a9ef88bd5d)

我按照您说的清空了日志然后刷新了页面，因为报错信息比较长，我分成了三个图发过来。还有一个事情我之前没有提及，我目前在国外，是不是会导致某些资源无法访问，供您参考，谢谢。

**Comment by LuckyPuppy514** [comment]
你截图的绝大部分都是无关信息，请像我这样，清空控制台后，点击切换按钮，然后截图

![20230707190130](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53246532/1b4ecbfd-00cb-4e2a-a29b-9258dd1f517a)

**Comment by xiaoyuanreadbook** [comment]
抱歉，我不知道还需要点击那个markdown的按钮才能使用，我还以为就是直接启用然后就会显示在网页上，现在已经可以正常使用了，之前我从没有写过专栏，望谅解，谢谢！
