### ISSUE TITLE
关于同一行内有多个行内公式

### ISSUE THREAD

**Issue by eleven-dimension** [LuckyPuppy514/Bilibili-Markdown#6]
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53202752/83c6ceb8-2875-4a5e-8179-d3c62cdb8e19)

你好，如图，解析是否有误？

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53246532/dc6f189e-c880-4154-ba5c-5e41031b69b6)

已修复，如果还不行请按下列操作清除浏览器缓存

1. F12 打开调试工具，找到网络，选择全部
2. 输入筛选内容 `https://www.lckp.top/bilibili-markdown/index.html`
3. 刷新页面，鼠标右键，清除浏览器缓存
4. 刷新页面

![1702607547517](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53246532/1bc38099-e786-4829-868a-16ebc1712ba0)

**Comment by eleven-dimension** [comment]
感谢，还有一个地方：

![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53202752/b8e9d423-6c6c-49a8-a230-52c805543691)

这里当同一行内的多个行内公式出现两个`_`会被解析成md的强调语法，可能需要特判？

**Comment by eleven-dimension** [comment]
`内容 $\mathbf{A}_{m,n}$ 内容$\mathbf{A}_{m,n}$ 内容。`

**Comment by eleven-dimension** [comment]
感谢，还有一个地方：
![image](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/53202752/b8c41690-324a-4398-ad2f-9dddf07fd0b5)
被解析成md的斜体强调了

测试的原文本：
```
内容 $\mathbf{A}_{m,n}$ 内容$\mathbf{A}_{m,n}$ 内容。


内容 $A_{m,n}$ 内容$A_{m,n}$ 内容。
```

不过GitHub的md也有这问题 :satisfied:

**Comment by LuckyPuppy514** [comment]
这个是B站的问题，没法处理的，实际上就是B站有个接口，公式传过去会返回一张图片，例如

`https://api.bilibili.com/x/web-frontend/mathjax/tex?formula=A_%7Bm%2Cn%7D`

![](https://api.bilibili.com/x/web-frontend/mathjax/tex?formula=A_%7Bm%2Cn%7D)
