### ISSUE TITLE
Bilibili 专栏出了一个新的编辑器，请问可以适配吗？

### ISSUE THREAD

**Issue by jiangbo** [LuckyPuppy514/Bilibili-Markdown#8]
有一个新的编辑器和一个老的编辑器，老的编辑器现在可以使用，新的好像还不行？
![1703556082255](https://github.com/LuckyPuppy514/Bilibili-Markdown/assets/14179422/a1e90fa4-de22-4619-a675-5feed0e17594)

**Comment by LuckyPuppy514** [comment]
看了下，界面和解析器都得重新适配，比较麻烦，先用旧版编辑器转吧😢

**Comment by jiangbo** [comment]
好，谢谢。
